"""
Brand override — copy this file as `brand-override.local.py` into the working
directory where you'll run the skill. The build scripts auto-load it.

The skill ships with the CS2 brand by default (Chad Stamm — author/maintainer
brand: Algarve teal accent + RUMO blue text + Sand background + terracotta, Montserrat + Open Sans).
This file shows the override structure. Leave a value at None to inherit the
default.
"""

# Color palette
ACCENT_COLOR = "#0070f3"          # Primary accent — links, copy buttons, focus states
ACCENT_HOVER = "#0051cc"          # Hover state for accent
TEXT_PRIMARY = "#111827"          # Main body text
TEXT_SECONDARY = "#4b5563"        # Secondary / muted text
BORDER_COLOR = "#e5e7eb"          # Field borders, dividers
BG_PRIMARY = "#ffffff"            # Page background
BG_SECONDARY = "#f9fafb"          # Card / section background
BG_TERTIARY = "#f3f4f6"           # Subtle highlights
SUCCESS_COLOR = "#10b981"         # "Copied" confirmation

# Typography
FONT_FAMILY_BODY = '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif'
FONT_FAMILY_HEADING = '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif'
FONT_FAMILY_MONO = '"JetBrains Mono", "Monaco", "Menlo", monospace'

# Optional Google Fonts URL — set to None to skip the <link> and rely on system
# fallbacks specified above. The default skill ships Montserrat + Open Sans;
# match this URL to the font families above.
GOOGLE_FONTS_URL = "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap"

# Logo (optional)
# Provide either a data URI (recommended for self-contained HTML) or a public URL.
# To embed an image as data URI:
#   import base64
#   LOGO_DATA_URI = "data:image/png;base64," + base64.b64encode(open("logo.png","rb").read()).decode()
LOGO_DATA_URI = None              # e.g., "data:image/png;base64,iVBORw0KGgo..."
LOGO_ALT_TEXT = "Your Brand"
LOGO_HEIGHT_PX = 40

# Footer
FOOTER_LEFT = "Generated by hubspot-ai-context — https://github.com/chadstamm/claude-skill-hubspot-ai-context"
FOOTER_RIGHT = None               # e.g., a build timestamp or attribution


# ---------------------------------------------------------------------------
# Annotated branded example (commented out below — uncomment + edit to use)
# ---------------------------------------------------------------------------
#
# Below is an example of what a real branded override looks like. Don't ship
# someone else's brand by accident — replace every value with your own.
#
# ACCENT_COLOR = "#FF6B35"        # Bold orange
# ACCENT_HOVER = "#E55A2B"
# TEXT_PRIMARY = "#1A1A1A"
# TEXT_SECONDARY = "#6B6B6B"
# BORDER_COLOR = "#E0E0E0"
# BG_PRIMARY = "#FFFFFF"
# BG_SECONDARY = "#FAFAFA"
# BG_TERTIARY = "#F0F0F0"
# SUCCESS_COLOR = "#2EA043"
#
# FONT_FAMILY_BODY = '"Montserrat", system-ui, sans-serif'
# FONT_FAMILY_HEADING = '"Montserrat", system-ui, sans-serif'
#
# LOGO_DATA_URI = "data:image/png;base64,..."   # Your base64-encoded logo
# LOGO_ALT_TEXT = "Your Company Name"
# LOGO_HEIGHT_PX = 48
#
# FOOTER_LEFT = "Built by [Your Team] · Source: output/[client]-data.json"
# FOOTER_RIGHT = "v1.0"
