#!/usr/bin/env python3
"""Build a click-to-copy HubSpot ICP paste sheet from a CSV.

Usage:
    python build_icp_html.py path/to/icps.csv [output.html]

CSV schema in templates/icp-library.example.csv. Columns:
  Grouping, Category, Name, Description, Business Type, Job Titles, Industry,
  Location, Company Size, Revenue, Age Range, Interests, Other, Slug

Field rendering matches HubSpot's Create ICP form behavior:
  - Location → click-to-copy pills (HubSpot picklist tags)
  - Job Titles, Industry, Company Size, Revenue, Age Range, Interests → semicolon-separated text + Copy
  - Name, Other, Description, Business Type → single Copy

Brand overrides: if a file named `brand-override.local.py` exists in the
current working directory, its module-level constants override the defaults.
"""

import argparse
import csv
import html
import importlib.util
import re
import sys
from pathlib import Path
from types import SimpleNamespace


# CS2 brand defaults (Chad Stamm — author/maintainer brand)
# Override with brand-override.local.py in the user's working directory.
DEFAULT_BRAND = SimpleNamespace(
    ACCENT_COLOR="#DA5525",        # Terracotta orange
    ACCENT_HOVER="#B8431D",
    TEXT_PRIMARY="#0C2340",        # Yankee blue
    TEXT_SECONDARY="#1F628E",      # Ocean blue
    BORDER_COLOR="#A6A6A6",        # Ash gray
    BG_PRIMARY="#FFFFFF",
    BG_SECONDARY="#FAF6F1",        # Sand
    BG_TERTIARY="#F0EBE3",
    SUCCESS_COLOR="#1EBEB1",       # Signature teal
    FONT_FAMILY_BODY='"Open Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    FONT_FAMILY_HEADING='"Montserrat", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    FONT_FAMILY_MONO='"JetBrains Mono", "Menlo", "Monaco", monospace',
    GOOGLE_FONTS_URL="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&family=Open+Sans:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap",
    LOGO_DATA_URI=None,
    LOGO_ALT_TEXT=None,
    LOGO_HEIGHT_PX=40,
    FOOTER_LEFT="Generated by hubspot-ai-context — github.com/chadstamm/claude-skill-hubspot-ai-context",
    FOOTER_RIGHT=None,
)

# HubSpot's Create ICP form order (verified 2026-05-04)
FIELD_ORDER = [
    "Name",
    "Job Titles",
    "Industry",
    "Location",
    "Company Size",
    "Revenue",
    "Age Range",
    "Interests",
    "Other",
    # Extras not in the official Create ICP form, kept for AI context
    "Description",
    "Business Type",
]

# Render each field according to HubSpot's actual UI behavior
PILL_FIELDS = {"Location"}  # HubSpot Location is one-tag-at-a-time
SEMICOLON_TEXT_FIELDS = {
    "Job Titles", "Industry", "Company Size",
    "Revenue", "Age Range", "Interests"
}
# Name, Other, Description, Business Type fall through to single-value text


def load_brand() -> SimpleNamespace:
    override_path = Path.cwd() / "brand-override.local.py"
    if not override_path.exists():
        return DEFAULT_BRAND
    spec = importlib.util.spec_from_file_location("brand_override", override_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    brand = SimpleNamespace(**vars(DEFAULT_BRAND))
    for key in vars(DEFAULT_BRAND):
        if hasattr(module, key):
            value = getattr(module, key)
            if value is not None:
                setattr(brand, key, value)
    return brand


def esc(value) -> str:
    if value is None:
        return ""
    return html.escape(str(value))


def attr(value) -> str:
    return html.escape(str(value or ""), quote=True)


def slugify(text: str) -> str:
    s = text.lower()
    s = re.sub(r"[^a-z0-9 \-]", "", s)
    s = s.replace(" ", "-")
    return re.sub(r"-+", "-", s).strip("-")


def split_items(value: str) -> list:
    """Split a multi-value field. Prefer semicolon when present, fall back to comma."""
    s = (value or "").replace("\n", " ").strip()
    if not s:
        return []
    sep = ";" if ";" in s else ","
    items = [t.strip() for t in s.split(sep)]
    return [t for t in items if t]


def render_pill_field(label: str, value: str) -> str:
    items = split_items(value)
    if not items:
        return ""
    pills_html = "".join(
        f'<button class="pill" data-copy="{attr(i)}" title="Click to copy">'
        f'<span class="pill-text">{esc(i)}</span>'
        f'<span class="pill-icon" aria-hidden="true">⧉</span>'
        f'</button>'
        for i in items
    )
    join_str = "; ".join(items)
    return f"""
<div class="field">
  <div class="field-label">{esc(label)}</div>
  <div class="field-hint">Click any tag to copy it individually, or use Copy all below.</div>
  <div class="pills">{pills_html}</div>
  <button class="copy-all" data-copy="{attr(join_str)}">Copy all ({len(items)})</button>
</div>"""


def render_semicolon_text(label: str, value: str) -> str:
    items = split_items(value)
    if not items:
        return ""
    joined = "; ".join(items)
    return f"""
<div class="field">
  <div class="field-label">{esc(label)}</div>
  <div class="field-value"><p>{esc(joined)}</p></div>
  <button class="copy-btn" data-copy="{attr(joined)}">Copy</button>
</div>"""


def render_text(label: str, value: str) -> str:
    if not value:
        return ""
    # Preserve paragraph breaks for "Other" multi-paragraph content
    paras = re.split(r"\n\s*\n", value.strip())
    paras_html = "".join(f"<p>{esc(p)}</p>" for p in paras if p)
    return f"""
<div class="field">
  <div class="field-label">{esc(label)}</div>
  <div class="field-value">{paras_html}</div>
  <button class="copy-btn" data-copy="{attr(value)}">Copy</button>
</div>"""


def render_field(label: str, value: str) -> str:
    if not value:
        return ""
    if label in PILL_FIELDS:
        return render_pill_field(label, value)
    if label in SEMICOLON_TEXT_FIELDS:
        return render_semicolon_text(label, value)
    return render_text(label, value)


def render_icp_card(icp: dict, num: int) -> str:
    name = icp.get("Name", "Unnamed").strip()
    category = icp.get("Category", "").strip()
    grouping = icp.get("Grouping", "").strip()
    slug = icp.get("Slug", "").strip() or slugify(name)
    fields_html = "\n".join(render_field(label, icp.get(label, "")) for label in FIELD_ORDER)

    # Copy-all-fields for the whole ICP
    parts = []
    for label in FIELD_ORDER:
        v = (icp.get(label) or "").strip()
        if not v:
            continue
        if label in (PILL_FIELDS | SEMICOLON_TEXT_FIELDS):
            v = "; ".join(split_items(v))
        parts.append(f"=== {label.upper()} ===\n{v}")
    copy_all_text = "\n\n".join(parts)

    meta = " · ".join(p for p in [grouping, category] if p)

    return f"""
<article class="icp" id="{esc(slug)}">
  <div class="icp-header">
    <div class="icp-num">{num}</div>
    <div>
      <h2>{esc(name)}</h2>
      <div class="icp-meta">{esc(meta)}</div>
    </div>
    <button class="copy-all" data-copy="{attr(copy_all_text)}">Copy all fields</button>
  </div>
  {fields_html}
</article>"""


def build_html(rows: list, brand: SimpleNamespace, source_name: str) -> str:
    cards_html = "\n".join(render_icp_card(row, i + 1) for i, row in enumerate(rows))

    # Build TOC
    toc_items = []
    for i, row in enumerate(rows):
        slug = (row.get("Slug") or slugify(row.get("Name", ""))).strip()
        name = row.get("Name", "").strip()
        toc_items.append(f'<li><a href="#{esc(slug)}">{i+1}. {esc(name)}</a></li>')
    toc_html = f'<ol class="toc">{"".join(toc_items)}</ol>'

    logo_html = ""
    if brand.LOGO_DATA_URI:
        logo_html = f'<img class="logo" src="{attr(brand.LOGO_DATA_URI)}" alt="{attr(brand.LOGO_ALT_TEXT or "")}" style="height: {brand.LOGO_HEIGHT_PX}px">'

    css = f"""
:root {{
  --accent: {brand.ACCENT_COLOR};
  --accent-deep: {brand.ACCENT_HOVER};
  --accent-soft: color-mix(in srgb, var(--accent) 8%, transparent);
  --accent-line: color-mix(in srgb, var(--accent) 22%, transparent);
  --accent-glow: color-mix(in srgb, var(--accent) 35%, transparent);
  --ink: {brand.TEXT_PRIMARY};
  --ink-soft: {brand.TEXT_SECONDARY};
  --ink-mute: #6F6A5E;
  --ink-faint: #9A9285;
  --rumo: #1A2744;
  --rumo-line: color-mix(in srgb, var(--rumo) 22%, transparent);
  --paper: {brand.BG_PRIMARY};
  --paper-warm: {brand.BG_SECONDARY};
  --paper-deep: {brand.BG_TERTIARY};
  --rule: color-mix(in srgb, {brand.BORDER_COLOR} 50%, transparent);
  --success: {brand.SUCCESS_COLOR};
  --serif: {brand.FONT_FAMILY_HEADING};
  --sans: {brand.FONT_FAMILY_BODY};
  --mono: {brand.FONT_FAMILY_MONO};
  --lift-1: 0 1px 0 rgba(12, 35, 64, 0.04), 0 12px 28px -16px rgba(12, 35, 64, 0.10);
  --lift-2: 0 1px 0 rgba(12, 35, 64, 0.05), 0 18px 40px -20px rgba(12, 35, 64, 0.16);
  --ease: cubic-bezier(0.2, 0.8, 0.2, 1);
}}

*, *::before, *::after {{ box-sizing: border-box; }}
* {{ margin: 0; padding: 0; }}
html {{ -webkit-text-size-adjust: 100%; }}

body {{
  font-family: var(--sans);
  font-size: 16px; line-height: 1.65;
  color: var(--ink); background: var(--paper-warm);
  -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;
  font-feature-settings: "kern", "liga";
  min-height: 100vh; padding: 56px 24px 80px; position: relative;
}}

body::before {{
  content: ''; position: fixed; inset: 0; pointer-events: none;
  z-index: 100; opacity: 0.03; mix-blend-mode: multiply;
  background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='240' height='240'><filter id='n'><feTurbulence baseFrequency='0.9' seed='2'/></filter><rect width='100%25' height='100%25' filter='url(%23n)'/></svg>");
}}

body::after {{
  content: ''; position: fixed; inset: 0; pointer-events: none; z-index: -1;
  background:
    radial-gradient(ellipse 80% 60% at 15% 0%, color-mix(in srgb, var(--accent) 4%, transparent), transparent 60%),
    radial-gradient(ellipse 60% 50% at 90% 100%, color-mix(in srgb, var(--success) 3%, transparent), transparent 60%);
}}

::selection {{ background: var(--accent); color: var(--paper); }}

a {{
  color: var(--accent); text-decoration: none;
  border-bottom: 1px solid var(--accent-line);
  transition: border-color 180ms var(--ease), color 180ms var(--ease);
}}
a:hover {{ border-bottom-color: var(--accent); color: var(--accent-deep); }}

button:focus-visible, a:focus-visible {{
  outline: 2px solid var(--accent); outline-offset: 3px; border-radius: 2px;
}}

.container {{ max-width: 880px; margin: 0 auto; }}

.header {{
  position: relative; background: var(--paper);
  padding: 64px 56px 48px; margin-bottom: 32px;
  border: 1px solid var(--rule); border-radius: 4px;
  box-shadow: var(--lift-1); overflow: hidden;
}}
.header::before {{
  content: ''; position: absolute; top: 0; left: 0;
  width: 96px; height: 5px; background: var(--accent);
}}
.header::after {{
  content: 'ICP'; position: absolute; bottom: 16px; right: 24px;
  font-family: var(--mono); font-size: 9px; font-weight: 500;
  letter-spacing: 0.32em; color: var(--ink-faint); pointer-events: none;
}}
.header h1 {{
  font-family: var(--serif);
  font-size: clamp(28px, 3.5vw, 38px); font-weight: 700;
  line-height: 1.08; letter-spacing: -0.02em;
  color: var(--ink); text-wrap: balance; margin: 0 0 6px;
}}
.subtitle {{
  font-family: var(--serif);
  font-size: 11px; font-weight: 700;
  letter-spacing: 0.22em; text-transform: uppercase;
  color: var(--accent); margin-bottom: 24px;
  display: flex; align-items: center; gap: 10px;
}}
.subtitle::before {{
  content: ''; display: inline-block;
  width: 24px; height: 1px; background: var(--accent);
}}

.toc {{
  margin: 24px 0 0; padding-left: 0; list-style: none;
  columns: 2; column-gap: 32px; counter-reset: toc-counter;
}}
.toc li {{
  margin-bottom: 6px; font-size: 13px;
  font-family: var(--sans); break-inside: avoid;
  counter-increment: toc-counter;
}}
.toc a {{
  color: var(--ink-soft); border-bottom: none;
  transition: color 160ms var(--ease);
}}
.toc a:hover {{ color: var(--accent); }}

.icp {{
  position: relative; background: var(--paper);
  padding: 36px 40px 32px 44px; margin-bottom: 16px;
  border: 1px solid var(--rule); border-radius: 4px;
  box-shadow: var(--lift-1);
  transition: box-shadow 280ms var(--ease);
}}
.icp::before {{
  content: ''; position: absolute;
  top: 36px; bottom: 36px; left: 0; width: 3px;
  background: var(--accent); border-radius: 0 2px 2px 0;
  transition: top 280ms var(--ease), bottom 280ms var(--ease);
}}
.icp:hover {{ box-shadow: var(--lift-2); }}
.icp:hover::before {{ top: 28px; bottom: 28px; }}

.icp-header {{
  display: flex; align-items: center; gap: 18px;
  padding-bottom: 20px; margin-bottom: 22px;
  border-bottom: 1px solid var(--rule);
}}
.icp-num {{
  background: var(--accent); color: var(--paper);
  width: 42px; height: 42px;
  border-radius: 4px; display: flex; align-items: center; justify-content: center;
  font-weight: 700; flex-shrink: 0;
  font-family: var(--mono); font-size: 14px;
  letter-spacing: 0.04em;
}}
.icp-header h2 {{
  margin: 0; font-size: 22px;
  font-family: var(--serif); font-weight: 700;
  letter-spacing: -0.01em; color: var(--ink);
}}
.icp-meta {{
  font-family: var(--serif);
  font-size: 10px; font-weight: 600;
  color: var(--ink-mute); margin-top: 4px;
  text-transform: uppercase; letter-spacing: 0.18em;
}}
.icp-header .copy-all {{ margin-left: auto; }}

.field {{
  padding: 20px 0; border-bottom: 1px dashed var(--rule);
}}
.field:last-child {{ border-bottom: none; padding-bottom: 0; }}
.field:first-child {{ padding-top: 0; }}

.field-label {{
  font-family: var(--serif); font-size: 11px; font-weight: 700;
  letter-spacing: 0.18em; text-transform: uppercase;
  color: var(--rumo); margin-bottom: 8px;
  display: flex; align-items: baseline; gap: 14px;
}}
.field-label::after {{
  content: ''; flex: 1; height: 1px;
  background: var(--rumo-line);
  position: relative; bottom: 3px;
}}
.field-hint {{
  font-family: var(--sans); font-size: 13px; font-style: italic;
  color: var(--ink-mute); margin-bottom: 14px; letter-spacing: 0.005em;
}}
.field-value {{
  font-family: var(--sans); font-size: 15px; line-height: 1.7;
  color: var(--ink-soft); margin-bottom: 14px;
}}
.field-value p {{ margin-bottom: 12px; text-wrap: pretty; }}
.field-value p:last-child {{ margin-bottom: 0; }}

.pills {{ display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 14px; }}
.pill {{
  display: inline-flex; align-items: center; gap: 8px;
  font-family: var(--mono); font-size: 12px; font-weight: 500;
  letter-spacing: 0.005em; color: var(--ink);
  background: var(--paper-deep); border: 1px solid transparent;
  padding: 7px 12px; border-radius: 3px; cursor: pointer;
  transition: all 180ms var(--ease); font-feature-settings: "tnum";
}}
.pill .pill-text {{ line-height: 1; }}
.pill .pill-icon {{
  font-size: 11px; color: var(--ink-faint); line-height: 1;
  transition: color 180ms var(--ease), transform 180ms var(--ease);
}}
.pill:hover {{
  background: var(--accent-soft); border-color: var(--accent);
  color: var(--accent-deep); transform: translateY(-1px);
}}
.pill:hover .pill-icon {{ color: var(--accent); transform: scale(1.1); }}
.pill.copied {{ background: var(--success); border-color: var(--success); color: var(--paper); }}
.pill.copied .pill-icon {{ color: var(--paper); }}

.copy-btn, .copy-all {{
  display: inline-flex; align-items: center; gap: 6px;
  font-family: var(--serif); font-size: 11px; font-weight: 700;
  letter-spacing: 0.16em; text-transform: uppercase;
  color: var(--paper); background: var(--accent);
  border: none; padding: 11px 20px; border-radius: 3px; cursor: pointer;
  transition: background 180ms var(--ease), transform 180ms var(--ease), box-shadow 240ms var(--ease);
}}
.copy-btn:hover, .copy-all:hover {{
  background: var(--accent-deep); transform: translateY(-1px);
  box-shadow: 0 8px 16px -8px var(--accent-glow);
}}
.copy-btn:active, .copy-all:active {{ transform: translateY(0); }}
.copy-btn.copied, .copy-all.copied {{ background: var(--success); }}

.footer {{
  margin-top: 56px; padding: 24px 0 0;
  border-top: 1px solid var(--rule);
  display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 12px;
  font-family: var(--mono); font-size: 10px; letter-spacing: 0.06em; color: var(--ink-faint);
}}
.logo {{ vertical-align: middle; margin-bottom: 24px; display: block; }}

@media (max-width: 720px) {{
  body {{ padding: 32px 16px 48px; }}
  .header {{ padding: 40px 28px 32px; }}
  .header h1 {{ font-size: 26px; }}
  .icp {{ padding: 28px 24px 24px 32px; }}
  .icp-header {{ flex-wrap: wrap; }}
  .icp-header .copy-all {{ margin-left: 0; margin-top: 8px; }}
  .toc {{ columns: 1; }}
}}

@media print {{
  body {{ background: white; padding: 24px; }}
  body::before, body::after {{ display: none; }}
  .icp, .header {{ box-shadow: none; page-break-inside: avoid; }}
  .copy-btn, .copy-all, .pill .pill-icon {{ display: none; }}
}}
"""

    js = """
document.addEventListener('click', (e) => {
  const btn = e.target.closest('[data-copy]');
  if (!btn) return;
  const text = btn.getAttribute('data-copy');
  navigator.clipboard.writeText(text).then(() => {
    btn.classList.add('copied');
    const originalHtml = btn.innerHTML;
    if (btn.classList.contains('pill')) {
      btn.innerHTML = '<span class="pill-text">✓ Copied</span>';
    } else {
      btn.innerHTML = '✓ Copied';
    }
    setTimeout(() => {
      btn.classList.remove('copied');
      btn.innerHTML = originalHtml;
    }, 1200);
  });
});
"""

    footer_left = brand.FOOTER_LEFT or ""
    footer_right = brand.FOOTER_RIGHT or ""

    fonts_link = (
        f'<link rel="preconnect" href="https://fonts.googleapis.com">'
        f'<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
        f'<link rel="stylesheet" href="{attr(brand.GOOGLE_FONTS_URL)}">'
        if getattr(brand, "GOOGLE_FONTS_URL", None) else ""
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>HubSpot ICPs — {esc(source_name)}</title>
{fonts_link}
<style>{css}</style>
</head>
<body>
<div class="container">
  <div class="header">
    {logo_html}
    <h1>HubSpot Ideal Customer Profiles</h1>
    <div class="subtitle">Source: {esc(source_name)} · {len(rows)} ICPs · Field-by-field paste sheet</div>
    {toc_html}
  </div>
  {cards_html}
  <div class="footer">
    <div>{esc(footer_left)}</div>
    <div>{esc(footer_right)}</div>
  </div>
</div>
<script>{js}</script>
</body>
</html>
"""


def main():
    parser = argparse.ArgumentParser(description="Build HubSpot ICP paste sheet HTML from CSV")
    parser.add_argument("csv_path", help="Path to ICP CSV file")
    parser.add_argument("output_path", nargs="?", help="Output HTML path (defaults to alongside CSV)")
    args = parser.parse_args()

    csv_path = Path(args.csv_path)
    if not csv_path.exists():
        print(f"Error: CSV not found: {csv_path}", file=sys.stderr)
        sys.exit(1)

    with csv_path.open() as f:
        rows = list(csv.DictReader(f))
    if not rows:
        print(f"Error: CSV is empty: {csv_path}", file=sys.stderr)
        sys.exit(1)

    if args.output_path:
        out_path = Path(args.output_path)
    else:
        out_path = csv_path.parent / f"{csv_path.stem}-icps.html"

    brand = load_brand()
    html_str = build_html(rows, brand, csv_path.stem)
    out_path.write_text(html_str)
    print(f"Wrote {out_path} ({out_path.stat().st_size:,} bytes, {len(rows)} ICPs)")


if __name__ == "__main__":
    main()
