#!/usr/bin/env python3
"""Build a click-to-copy HubSpot Company Context paste sheet from a JSON data dict.

Usage:
    python build_company_context_html.py path/to/data.json [output.html]

The JSON schema is documented in templates/company-context-data.example.json.

Brand overrides: if a file named `brand-override.local.py` exists in the
current working directory, its module-level constants override the defaults.
"""

import argparse
import html
import importlib.util
import json
import re
import sys
from pathlib import Path
from types import SimpleNamespace


# CS2 brand defaults (Chad Stamm — author/maintainer brand)
# Override with brand-override.local.py in the user's working directory.
DEFAULT_BRAND = SimpleNamespace(
    ACCENT_COLOR="#DA5525",        # Terracotta orange — primary accent
    ACCENT_HOVER="#B8431D",        # Darker terracotta for hover
    TEXT_PRIMARY="#0C2340",        # Yankee blue — text on light
    TEXT_SECONDARY="#1F628E",      # Ocean blue — secondary text
    BORDER_COLOR="#A6A6A6",        # Ash gray — borders, dividers
    BG_PRIMARY="#FFFFFF",          # Paper white
    BG_SECONDARY="#FAF6F1",        # Sand — warm-white default
    BG_TERTIARY="#F0EBE3",         # Slightly darker sand
    SUCCESS_COLOR="#1EBEB1",       # Signature teal — action / confirmation
    FONT_FAMILY_BODY='"Open Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    FONT_FAMILY_HEADING='"Montserrat", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    FONT_FAMILY_MONO='"JetBrains Mono", "Menlo", "Monaco", monospace',
    GOOGLE_FONTS_URL="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&family=Open+Sans:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap",
    LOGO_DATA_URI=None,
    LOGO_ALT_TEXT=None,
    LOGO_HEIGHT_PX=40,
    FOOTER_LEFT="Generated by hubspot-ai-context — github.com/chadstamm/claude-skill-hubspot-ai-context",
    FOOTER_RIGHT=None,
)


def load_brand() -> SimpleNamespace:
    """Load brand-override.local.py from CWD if present, else use defaults."""
    override_path = Path.cwd() / "brand-override.local.py"
    if not override_path.exists():
        return DEFAULT_BRAND
    spec = importlib.util.spec_from_file_location("brand_override", override_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    brand = SimpleNamespace(**vars(DEFAULT_BRAND))
    for key in vars(DEFAULT_BRAND):
        if hasattr(module, key):
            value = getattr(module, key)
            if value is not None:
                setattr(brand, key, value)
    return brand


def esc(value) -> str:
    if value is None:
        return ""
    return html.escape(str(value))


def attr(value) -> str:
    return html.escape(str(value or ""), quote=True)


def render_pill_field(label: str, items: list, copy_all_label: str = None) -> str:
    """Multi-tag field with click-to-copy on each pill + Copy-All button."""
    if not items:
        return ""
    pills_html = "".join(
        f'<button class="pill" data-copy="{attr(i)}" title="Click to copy">'
        f'<span class="pill-text">{esc(i)}</span>'
        f'<span class="pill-icon" aria-hidden="true">⧉</span>'
        f'</button>'
        for i in items
    )
    join_str = "; ".join(items)
    return f"""
<div class="field">
  <div class="field-label">{esc(label)}</div>
  <div class="field-hint">Click any tag to copy it individually, or use Copy all below.</div>
  <div class="pills">{pills_html}</div>
  <button class="copy-all" data-copy="{attr(join_str)}">Copy all ({len(items)})</button>
</div>"""


def render_text_field(label: str, value: str, mono: bool = False) -> str:
    """Single-value text field with one Copy button."""
    if not value:
        return ""
    css_class = "field-value field-value--mono" if mono else "field-value"
    return f"""
<div class="field">
  <div class="field-label">{esc(label)}</div>
  <div class="{css_class}"><p>{esc(value)}</p></div>
  <button class="copy-btn" data-copy="{attr(value)}">Copy</button>
</div>"""


def render_pain_points(pain_points: list) -> str:
    """Pain points: bolded label + paragraph, single Copy for the entire field
    (HubSpot's pain points field accepts one bulk paste)."""
    if not pain_points:
        return ""
    items_html = []
    full_text_parts = []
    for label, body in pain_points:
        full_text_parts.append(f"**{label}** {body}")
        items_html.append(
            f'<div class="pain-item"><p><strong>{esc(label)}</strong> {esc(body)}</p></div>'
        )
    full_text = "\n\n".join(full_text_parts)
    return f"""
<div class="field">
  <div class="field-label">What pain points does your company solve?</div>
  <div class="field-value">{''.join(items_html)}</div>
  <button class="copy-btn" data-copy="{attr(full_text)}">Copy</button>
</div>"""


def render_products(products: list) -> str:
    """HubSpot's Itemized Products field has separate Product Name and
    Description columns — give each a Copy button so they can be pasted
    into their respective HubSpot fields independently."""
    if not products:
        return ""
    rows = []
    for p in products:
        title = p.get("title", "")
        url = p.get("url", "")
        models = p.get("models", "")
        blurb = p.get("blurb", "")
        rows.append(f"""
<tr>
  <td>
    <strong>{esc(title)}</strong>
    <button class="copy-btn copy-btn--mini" data-copy="{attr(title)}">Copy name</button>
    <div class="product-meta">
      <span class="mono">{esc(models)}</span>
      {('<br><a href="' + attr(url) + '" target="_blank">' + esc(url) + '</a>') if url else ''}
    </div>
  </td>
  <td>
    <div class="product-blurb">{esc(blurb)}</div>
    <button class="copy-btn copy-btn--mini" data-copy="{attr(blurb)}">Copy description</button>
  </td>
</tr>""")
    return f"""
<div class="field">
  <div class="field-label">Itemized products or services</div>
  <div class="field-hint">Product Name and Description are separate fields in HubSpot — copy each independently.</div>
  <table class="products-table">
    <thead><tr><th>Product Name</th><th>Description</th></tr></thead>
    <tbody>{''.join(rows)}</tbody>
  </table>
</div>"""


def render_industry_classification(rows: list) -> str:
    if not rows:
        return ""
    items_html = []
    for row in rows:
        items_html.append(f"""
<tr>
  <td><strong>{esc(row.get('field',''))}</strong></td>
  <td>{esc(row.get('value',''))}</td>
  <td><button class="copy-btn" data-copy="{attr(row.get('value',''))}">Copy</button></td>
  <td><span class="note">{esc(row.get('note',''))}</span></td>
</tr>""")
    return f"""
<div class="field">
  <div class="field-label">Industry Classification</div>
  <table class="cls-table">
    <thead><tr><th>Field</th><th>Value</th><th></th><th>Note</th></tr></thead>
    <tbody>{''.join(items_html)}</tbody>
  </table>
</div>"""


def render_competitors(competitors: list, note: str = "") -> str:
    """HubSpot's Main Competitors entry has separate fields for company name,
    URL, and competitive areas. Give each its own Copy button. Description
    is shown for context but not copyable (it's notes, not a HubSpot field)."""
    if not competitors:
        return ""
    items_html = []
    for c in competitors:
        name = c.get("name", "")
        domain = c.get("domain", "")
        areas = "; ".join(c.get("areas", []))
        note_text = c.get("note", "")
        items_html.append(f"""
<div class="competitor">
  <div class="competitor-row">
    <div class="competitor-row-label">Name</div>
    <div class="competitor-row-value"><strong>{esc(name)}</strong></div>
    <button class="copy-btn copy-btn--mini" data-copy="{attr(name)}">Copy</button>
  </div>
  <div class="competitor-row competitor-row--note">
    <div class="competitor-row-label">Notes</div>
    <div class="competitor-row-value">{esc(note_text)}</div>
  </div>
  <div class="competitor-row">
    <div class="competitor-row-label">URL</div>
    <div class="competitor-row-value"><a href="https://{attr(domain)}" target="_blank">{esc(domain)}</a></div>
    <button class="copy-btn copy-btn--mini" data-copy="{attr(domain)}">Copy</button>
  </div>
  <div class="competitor-row">
    <div class="competitor-row-label">Competitive Areas</div>
    <div class="competitor-row-value">{esc(areas)}</div>
    <button class="copy-btn copy-btn--mini" data-copy="{attr(areas)}">Copy</button>
  </div>
</div>""")
    note_html = f'<div class="note">{esc(note)}</div>' if note else ""
    return f"""
<div class="field">
  <div class="field-label">Main Competitors</div>
  <div class="field-hint">Each competitor has separate Copy buttons for Name, URL, and Competitive Areas — paste each into the matching HubSpot field.</div>
  {''.join(items_html)}
  {note_html}
</div>"""


def render_replacement_rules(rules: list, note: str = "") -> str:
    if not rules:
        return ""
    rows = []
    for r in rules:
        f, t = r.get("from", ""), r.get("to", "")
        rows.append(f"""
<tr>
  <td><span class="mono">{esc(f)}</span></td>
  <td><span class="mono">{esc(t)}</span></td>
  <td><button class="copy-btn" data-copy="{attr(f)}">Copy from</button></td>
  <td><button class="copy-btn" data-copy="{attr(t)}">Copy to</button></td>
</tr>""")
    note_html = f'<div class="note">{esc(note)}</div>' if note else ""
    return f"""
<div class="field">
  <div class="field-label">Replacement Rules</div>
  <table class="rules-table">
    <thead><tr><th>From</th><th>To</th><th></th><th></th></tr></thead>
    <tbody>{''.join(rows)}</tbody>
  </table>
  {note_html}
</div>"""


def render_open_items(items: list) -> str:
    if not items:
        return ""
    lis = "\n".join(f"<li>{i}</li>" for i in items)  # items may contain inline HTML
    return f"""
<div class="field">
  <div class="field-label">Open Items for Client Confirmation</div>
  <ol class="open-items">{lis}</ol>
</div>"""


def build_html(data: dict, brand: SimpleNamespace) -> str:
    client_name = data.get("client_name", "Client")
    research_date = data.get("research_date", "")

    sections = []
    sections.append(render_text_field("Value Proposition", data.get("value_proposition", "")))
    sections.append(render_pain_points(data.get("pain_points", [])))
    sections.append(render_products(data.get("products", [])))
    sections.append(render_pill_field("Personality (HubSpot picklist — max 4)", data.get("personality", [])))
    sections.append(render_pill_field("Default Tone (HubSpot picklist — max 4)", data.get("default_tone", [])))
    sections.append(render_text_field("Mission (≤ 50 words)", data.get("mission", "")))
    sections.append(render_pill_field("Terms to Avoid (≤ 20 words)", data.get("terms_to_avoid", [])))
    sections.append(render_replacement_rules(data.get("replacement_rules", []), data.get("replacement_note", "")))
    sections.append(render_industry_classification(data.get("industry_classification", [])))
    sections.append(render_pill_field("Industry-Related Tags", data.get("industry_tags", [])))
    sections.append(render_pill_field("Positive Brand Associations", data.get("positive_associations", [])))
    sections.append(render_text_field("Negative Brand Associations", data.get("negative_associations_note", "")))
    sections.append(render_pill_field("Competitive Advantages", data.get("competitive_advantages", [])))
    sections.append(render_competitors(data.get("competitors", []), data.get("competitors_note", "")))
    sections.append(render_pill_field("Primary Content Topics", data.get("content_topics", [])))
    sections.append(render_pill_field("Content Format Types", data.get("content_formats", [])))
    sections.append(render_pill_field("Technologies", data.get("technologies", [])))
    sections.append(render_pill_field("Technology Categories", data.get("tech_categories", [])))
    sections.append(render_text_field("Supported Social Causes", data.get("social_causes", "")))
    sections.append(render_text_field("Sustainability Initiatives", data.get("sustainability", "")))
    sections.append(render_open_items(data.get("open_items", [])))

    body = "\n".join(s for s in sections if s)

    logo_html = ""
    if brand.LOGO_DATA_URI:
        logo_html = f'<img class="logo" src="{attr(brand.LOGO_DATA_URI)}" alt="{attr(brand.LOGO_ALT_TEXT or "")}" style="height: {brand.LOGO_HEIGHT_PX}px">'

    css = f"""
:root {{
  --accent: {brand.ACCENT_COLOR};
  --accent-hover: {brand.ACCENT_HOVER};
  --text-primary: {brand.TEXT_PRIMARY};
  --text-secondary: {brand.TEXT_SECONDARY};
  --border: {brand.BORDER_COLOR};
  --bg-primary: {brand.BG_PRIMARY};
  --bg-secondary: {brand.BG_SECONDARY};
  --bg-tertiary: {brand.BG_TERTIARY};
  --success: {brand.SUCCESS_COLOR};
}}
* {{ box-sizing: border-box; }}
body {{
  font-family: {brand.FONT_FAMILY_BODY};
  color: var(--text-primary); background: var(--bg-secondary);
  margin: 0; padding: 32px 24px; line-height: 1.6;
  -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;
}}
h1, h2, h3 {{ font-family: {brand.FONT_FAMILY_HEADING}; font-weight: 700; letter-spacing: -0.01em; }}
a {{ color: var(--accent); text-decoration: none; }}
a:hover {{ text-decoration: underline; }}
.container {{ max-width: 960px; margin: 0 auto; }}
.header {{
  background: var(--bg-primary); padding: 32px; border-radius: 16px;
  margin-bottom: 20px; border: 1px solid var(--border);
  box-shadow: 0 1px 3px rgba(12, 35, 64, 0.04);
}}
.header h1 {{ margin: 0 0 8px 0; font-size: 28px; }}
.subtitle {{ color: var(--text-secondary); font-size: 14px; }}
.field {{
  background: var(--bg-primary); padding: 24px; border-radius: 12px;
  margin-bottom: 14px; border: 1px solid var(--border);
  box-shadow: 0 1px 3px rgba(12, 35, 64, 0.04);
}}
.field-label {{
  font-family: {brand.FONT_FAMILY_HEADING}; font-weight: 600; font-size: 14px;
  text-transform: uppercase; letter-spacing: 0.05em;
  margin-bottom: 6px; color: var(--text-primary);
}}
.field-hint {{
  font-size: 13px; color: var(--text-secondary);
  margin-bottom: 12px; font-style: italic;
}}
.field-value p {{ margin: 0 0 10px 0; }}
.field-value p:last-child {{ margin-bottom: 0; }}
.field-value--mono {{ font-family: {brand.FONT_FAMILY_MONO}; }}
.note {{ font-size: 13px; color: var(--text-secondary); margin-top: 10px; font-style: italic; }}

.pills {{ display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 12px; }}
.pill {{
  display: inline-flex; align-items: center; gap: 6px;
  background: var(--bg-tertiary); border: 1px solid var(--border); color: var(--text-primary);
  padding: 6px 12px; border-radius: 999px; font-size: 13px; cursor: pointer;
  font-family: inherit; transition: all 150ms ease;
}}
.pill:hover {{ background: var(--accent); color: white; border-color: var(--accent); transform: translateY(-1px); }}
.pill.copied {{ background: var(--success); color: white; border-color: var(--success); }}
.pill-icon {{ font-size: 11px; opacity: 0.6; }}
.pill:hover .pill-icon {{ opacity: 1; }}

.copy-btn, .copy-all {{
  background: var(--accent); color: white; border: none;
  padding: 8px 14px; border-radius: 6px; cursor: pointer; font-size: 13px;
  font-family: inherit; font-weight: 500;
  transition: background 150ms ease;
}}
.copy-btn:hover, .copy-all:hover {{ background: var(--accent-hover); }}
.copy-btn.copied, .copy-all.copied {{ background: var(--success); }}
.copy-btn--inline {{ font-size: 12px; padding: 4px 10px; margin-left: 8px; }}
.copy-btn--mini {{ font-size: 11px; padding: 3px 8px; margin-left: 8px; vertical-align: middle; }}

table {{ width: 100%; border-collapse: collapse; margin-top: 8px; }}
th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid var(--border); vertical-align: top; font-size: 14px; }}
th {{
  font-family: {brand.FONT_FAMILY_HEADING}; font-weight: 600;
  text-transform: uppercase; letter-spacing: 0.04em; font-size: 12px;
  color: var(--text-secondary);
  background: var(--bg-tertiary);
}}
tbody tr:last-child td {{ border-bottom: none; }}
.mono, span.mono {{ font-family: {brand.FONT_FAMILY_MONO}; font-size: 13px; color: var(--text-secondary); }}
.product-meta {{ margin-top: 4px; font-size: 12px; }}
.product-blurb {{ margin-bottom: 6px; }}

.competitor {{
  padding: 16px; border: 1px solid var(--border); border-radius: 10px;
  margin-bottom: 12px; background: var(--bg-secondary);
}}
.competitor:last-child {{ margin-bottom: 0; }}
.competitor-row {{
  display: grid; grid-template-columns: 130px 1fr auto; gap: 12px;
  align-items: center; padding: 6px 0; border-bottom: 1px solid var(--border);
}}
.competitor-row:last-child {{ border-bottom: none; }}
.competitor-row--note {{ align-items: start; }}
.competitor-row--note .competitor-row-value {{ font-size: 13px; color: var(--text-secondary); padding: 4px 0; }}
.competitor-row-label {{
  font-family: {brand.FONT_FAMILY_HEADING}; font-weight: 600; font-size: 11px;
  text-transform: uppercase; letter-spacing: 0.05em; color: var(--text-secondary);
}}
.competitor-row-value {{ font-size: 14px; }}

.pain-item {{ padding: 12px 0; border-bottom: 1px solid var(--border); }}
.pain-item:last-child {{ border-bottom: none; padding-bottom: 0; }}
.pain-item:first-child {{ padding-top: 0; }}
.pain-item p {{ margin: 0; }}

.open-items {{ margin: 8px 0; padding-left: 24px; }}
.open-items li {{ margin-bottom: 8px; font-size: 14px; }}

.footer {{
  margin-top: 32px; padding: 20px 0; font-size: 12px; color: var(--text-secondary);
  display: flex; justify-content: space-between; flex-wrap: wrap; gap: 12px;
  border-top: 1px solid var(--border);
}}
.logo {{ vertical-align: middle; margin-bottom: 12px; display: block; }}
"""

    js = """
document.addEventListener('click', (e) => {
  const btn = e.target.closest('[data-copy]');
  if (!btn) return;
  const text = btn.getAttribute('data-copy');
  navigator.clipboard.writeText(text).then(() => {
    btn.classList.add('copied');
    // Preserve nested structure (pill-text/pill-icon) — flash via a data attr
    const originalHtml = btn.innerHTML;
    if (btn.classList.contains('pill')) {
      btn.innerHTML = '<span class="pill-text">✓ Copied</span>';
    } else {
      btn.innerHTML = '✓ Copied';
    }
    setTimeout(() => {
      btn.classList.remove('copied');
      btn.innerHTML = originalHtml;
    }, 1200);
  });
});
"""

    footer_left = brand.FOOTER_LEFT or ""
    footer_right = brand.FOOTER_RIGHT or ""

    fonts_link = (
        f'<link rel="preconnect" href="https://fonts.googleapis.com">'
        f'<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
        f'<link rel="stylesheet" href="{attr(brand.GOOGLE_FONTS_URL)}">'
        if getattr(brand, "GOOGLE_FONTS_URL", None) else ""
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(client_name)} — HubSpot Company Context</title>
{fonts_link}
<style>{css}</style>
</head>
<body>
<div class="container">
  <div class="header">
    {logo_html}
    <h1>{esc(client_name)} — HubSpot Company Context</h1>
    <div class="subtitle">Field-by-field paste sheet · Generated {esc(research_date)}</div>
  </div>
  {body}
  <div class="footer">
    <div>{esc(footer_left)}</div>
    <div>{esc(footer_right)}</div>
  </div>
</div>
<script>{js}</script>
</body>
</html>
"""


def main():
    parser = argparse.ArgumentParser(description="Build HubSpot Company Context paste sheet HTML")
    parser.add_argument("data_path", help="Path to JSON data dict")
    parser.add_argument("output_path", nargs="?", help="Output HTML path (defaults to alongside data file)")
    args = parser.parse_args()

    data_path = Path(args.data_path)
    if not data_path.exists():
        print(f"Error: data file not found: {data_path}", file=sys.stderr)
        sys.exit(1)

    data = json.loads(data_path.read_text())

    if args.output_path:
        out_path = Path(args.output_path)
    else:
        slug = data.get("client_slug", data_path.stem)
        out_path = data_path.parent / f"{slug}-hubspot-context.html"

    brand = load_brand()
    html_str = build_html(data, brand)
    out_path.write_text(html_str)
    print(f"Wrote {out_path} ({out_path.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
