#!/usr/bin/env python3
"""Build a click-to-copy HubSpot ICP paste sheet from a CSV.

Usage:
    python build_icp_html.py path/to/icps.csv [output.html]

CSV schema in templates/icp-library.example.csv. Columns:
  Grouping, Category, Name, Description, Business Type, Job Titles, Industry,
  Location, Company Size, Revenue, Age Range, Interests, Other, Slug

Field rendering matches HubSpot's Create ICP form behavior:
  - Location → click-to-copy pills (HubSpot picklist tags)
  - Job Titles, Industry, Company Size, Revenue, Age Range, Interests → semicolon-separated text + Copy
  - Name, Other, Description, Business Type → single Copy

Brand overrides: if a file named `brand-override.local.py` exists in the
current working directory, its module-level constants override the defaults.
"""

import argparse
import csv
import html
import importlib.util
import re
import sys
from pathlib import Path
from types import SimpleNamespace


# CS2 brand defaults (Chad Stamm — author/maintainer brand)
# Override with brand-override.local.py in the user's working directory.
DEFAULT_BRAND = SimpleNamespace(
    ACCENT_COLOR="#DA5525",        # Terracotta orange
    ACCENT_HOVER="#B8431D",
    TEXT_PRIMARY="#0C2340",        # Yankee blue
    TEXT_SECONDARY="#1F628E",      # Ocean blue
    BORDER_COLOR="#A6A6A6",        # Ash gray
    BG_PRIMARY="#FFFFFF",
    BG_SECONDARY="#FAF6F1",        # Sand
    BG_TERTIARY="#F0EBE3",
    SUCCESS_COLOR="#1EBEB1",       # Signature teal
    FONT_FAMILY_BODY='"Open Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    FONT_FAMILY_HEADING='"Montserrat", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    FONT_FAMILY_MONO='"JetBrains Mono", "Menlo", "Monaco", monospace',
    GOOGLE_FONTS_URL="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&family=Open+Sans:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap",
    LOGO_DATA_URI=None,
    LOGO_ALT_TEXT=None,
    LOGO_HEIGHT_PX=40,
    FOOTER_LEFT="Generated by hubspot-ai-context — github.com/chadstamm/claude-skill-hubspot-ai-context",
    FOOTER_RIGHT=None,
)

# HubSpot's Create ICP form order (verified 2026-05-04)
FIELD_ORDER = [
    "Name",
    "Job Titles",
    "Industry",
    "Location",
    "Company Size",
    "Revenue",
    "Age Range",
    "Interests",
    "Other",
    # Extras not in the official Create ICP form, kept for AI context
    "Description",
    "Business Type",
]

# Render each field according to HubSpot's actual UI behavior
PILL_FIELDS = {"Location"}  # HubSpot Location is one-tag-at-a-time
SEMICOLON_TEXT_FIELDS = {
    "Job Titles", "Industry", "Company Size",
    "Revenue", "Age Range", "Interests"
}
# Name, Other, Description, Business Type fall through to single-value text


def load_brand() -> SimpleNamespace:
    override_path = Path.cwd() / "brand-override.local.py"
    if not override_path.exists():
        return DEFAULT_BRAND
    spec = importlib.util.spec_from_file_location("brand_override", override_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    brand = SimpleNamespace(**vars(DEFAULT_BRAND))
    for key in vars(DEFAULT_BRAND):
        if hasattr(module, key):
            value = getattr(module, key)
            if value is not None:
                setattr(brand, key, value)
    return brand


def esc(value) -> str:
    if value is None:
        return ""
    return html.escape(str(value))


def attr(value) -> str:
    return html.escape(str(value or ""), quote=True)


def slugify(text: str) -> str:
    s = text.lower()
    s = re.sub(r"[^a-z0-9 \-]", "", s)
    s = s.replace(" ", "-")
    return re.sub(r"-+", "-", s).strip("-")


def split_items(value: str) -> list:
    """Split a multi-value field. Prefer semicolon when present, fall back to comma."""
    s = (value or "").replace("\n", " ").strip()
    if not s:
        return []
    sep = ";" if ";" in s else ","
    items = [t.strip() for t in s.split(sep)]
    return [t for t in items if t]


def render_pill_field(label: str, value: str) -> str:
    items = split_items(value)
    if not items:
        return ""
    pills_html = "".join(
        f'<button class="pill" data-copy="{attr(i)}" title="Click to copy">'
        f'<span class="pill-text">{esc(i)}</span>'
        f'<span class="pill-icon" aria-hidden="true">⧉</span>'
        f'</button>'
        for i in items
    )
    join_str = "; ".join(items)
    return f"""
<div class="field">
  <div class="field-label">{esc(label)}</div>
  <div class="field-hint">Click any tag to copy it individually, or use Copy all below.</div>
  <div class="pills">{pills_html}</div>
  <button class="copy-all" data-copy="{attr(join_str)}">Copy all ({len(items)})</button>
</div>"""


def render_semicolon_text(label: str, value: str) -> str:
    items = split_items(value)
    if not items:
        return ""
    joined = "; ".join(items)
    return f"""
<div class="field">
  <div class="field-label">{esc(label)}</div>
  <div class="field-value"><p>{esc(joined)}</p></div>
  <button class="copy-btn" data-copy="{attr(joined)}">Copy</button>
</div>"""


def render_text(label: str, value: str) -> str:
    if not value:
        return ""
    # Preserve paragraph breaks for "Other" multi-paragraph content
    paras = re.split(r"\n\s*\n", value.strip())
    paras_html = "".join(f"<p>{esc(p)}</p>" for p in paras if p)
    return f"""
<div class="field">
  <div class="field-label">{esc(label)}</div>
  <div class="field-value">{paras_html}</div>
  <button class="copy-btn" data-copy="{attr(value)}">Copy</button>
</div>"""


def render_field(label: str, value: str) -> str:
    if not value:
        return ""
    if label in PILL_FIELDS:
        return render_pill_field(label, value)
    if label in SEMICOLON_TEXT_FIELDS:
        return render_semicolon_text(label, value)
    return render_text(label, value)


def render_icp_card(icp: dict, num: int) -> str:
    name = icp.get("Name", "Unnamed").strip()
    category = icp.get("Category", "").strip()
    grouping = icp.get("Grouping", "").strip()
    slug = icp.get("Slug", "").strip() or slugify(name)
    fields_html = "\n".join(render_field(label, icp.get(label, "")) for label in FIELD_ORDER)

    # Copy-all-fields for the whole ICP
    parts = []
    for label in FIELD_ORDER:
        v = (icp.get(label) or "").strip()
        if not v:
            continue
        if label in (PILL_FIELDS | SEMICOLON_TEXT_FIELDS):
            v = "; ".join(split_items(v))
        parts.append(f"=== {label.upper()} ===\n{v}")
    copy_all_text = "\n\n".join(parts)

    meta = " · ".join(p for p in [grouping, category] if p)

    return f"""
<article class="icp" id="{esc(slug)}">
  <div class="icp-header">
    <div class="icp-num">{num}</div>
    <div>
      <h2>{esc(name)}</h2>
      <div class="icp-meta">{esc(meta)}</div>
    </div>
    <button class="copy-all" data-copy="{attr(copy_all_text)}">Copy all fields</button>
  </div>
  {fields_html}
</article>"""


def build_html(rows: list, brand: SimpleNamespace, source_name: str) -> str:
    cards_html = "\n".join(render_icp_card(row, i + 1) for i, row in enumerate(rows))

    # Build TOC
    toc_items = []
    for i, row in enumerate(rows):
        slug = (row.get("Slug") or slugify(row.get("Name", ""))).strip()
        name = row.get("Name", "").strip()
        toc_items.append(f'<li><a href="#{esc(slug)}">{i+1}. {esc(name)}</a></li>')
    toc_html = f'<ol class="toc">{"".join(toc_items)}</ol>'

    logo_html = ""
    if brand.LOGO_DATA_URI:
        logo_html = f'<img class="logo" src="{attr(brand.LOGO_DATA_URI)}" alt="{attr(brand.LOGO_ALT_TEXT or "")}" style="height: {brand.LOGO_HEIGHT_PX}px">'

    css = f"""
:root {{
  --accent: {brand.ACCENT_COLOR};
  --accent-hover: {brand.ACCENT_HOVER};
  --text-primary: {brand.TEXT_PRIMARY};
  --text-secondary: {brand.TEXT_SECONDARY};
  --border: {brand.BORDER_COLOR};
  --bg-primary: {brand.BG_PRIMARY};
  --bg-secondary: {brand.BG_SECONDARY};
  --bg-tertiary: {brand.BG_TERTIARY};
  --success: {brand.SUCCESS_COLOR};
}}
* {{ box-sizing: border-box; }}
body {{
  font-family: {brand.FONT_FAMILY_BODY};
  color: var(--text-primary); background: var(--bg-secondary);
  margin: 0; padding: 32px 24px; line-height: 1.6;
  -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;
}}
h1, h2, h3 {{ font-family: {brand.FONT_FAMILY_HEADING}; font-weight: 700; letter-spacing: -0.01em; }}
a {{ color: var(--accent); text-decoration: none; }}
a:hover {{ text-decoration: underline; }}
.container {{ max-width: 960px; margin: 0 auto; }}
.header {{
  background: var(--bg-primary); padding: 32px; border-radius: 16px;
  margin-bottom: 20px; border: 1px solid var(--border);
  box-shadow: 0 1px 3px rgba(12, 35, 64, 0.04);
}}
.header h1 {{ margin: 0 0 8px 0; font-size: 28px; }}
.subtitle {{ color: var(--text-secondary); font-size: 14px; margin-bottom: 16px; }}
.toc {{ margin: 0; padding-left: 24px; columns: 2; column-gap: 24px; }}
.toc li {{ margin-bottom: 6px; font-size: 14px; }}
.toc a {{ color: var(--accent); text-decoration: none; }}
.toc a:hover {{ text-decoration: underline; }}
.icp {{
  background: var(--bg-primary); padding: 28px; border-radius: 12px;
  margin-bottom: 14px; border: 1px solid var(--border);
  box-shadow: 0 1px 3px rgba(12, 35, 64, 0.04);
}}
.icp-header {{
  display: flex; align-items: center; gap: 16px;
  padding-bottom: 18px; margin-bottom: 18px; border-bottom: 1px solid var(--border);
}}
.icp-num {{
  background: var(--accent); color: white; width: 44px; height: 44px;
  border-radius: 50%; display: flex; align-items: center; justify-content: center;
  font-weight: 700; flex-shrink: 0; font-family: {brand.FONT_FAMILY_HEADING};
}}
.icp-header h2 {{ margin: 0; font-size: 22px; }}
.icp-meta {{ font-size: 12px; color: var(--text-secondary); margin-top: 4px; text-transform: uppercase; letter-spacing: 0.05em; }}
.icp-header .copy-all {{ margin-left: auto; }}
.field {{ padding: 18px 0; border-bottom: 1px solid var(--border); }}
.field:last-child {{ border-bottom: none; padding-bottom: 0; }}
.field-label {{
  font-family: {brand.FONT_FAMILY_HEADING}; font-weight: 600; font-size: 14px;
  text-transform: uppercase; letter-spacing: 0.05em;
  margin-bottom: 6px; color: var(--text-primary);
}}
.field-hint {{
  font-size: 13px; color: var(--text-secondary);
  margin-bottom: 12px; font-style: italic;
}}
.field-value p {{ margin: 0 0 8px 0; }}
.field-value p:last-child {{ margin-bottom: 0; }}
.pills {{ display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 12px; }}
.pill {{
  display: inline-flex; align-items: center; gap: 6px;
  background: var(--bg-tertiary); border: 1px solid var(--border); color: var(--text-primary);
  padding: 6px 12px; border-radius: 999px; font-size: 13px; cursor: pointer;
  font-family: inherit; transition: all 150ms ease;
}}
.pill:hover {{ background: var(--accent); color: white; border-color: var(--accent); transform: translateY(-1px); }}
.pill.copied {{ background: var(--success); color: white; border-color: var(--success); }}
.pill-icon {{ font-size: 11px; opacity: 0.6; }}
.pill:hover .pill-icon {{ opacity: 1; }}
.copy-btn, .copy-all {{
  background: var(--accent); color: white; border: none;
  padding: 8px 14px; border-radius: 6px; cursor: pointer; font-size: 13px;
  font-family: inherit; font-weight: 500;
  transition: background 150ms ease;
}}
.copy-btn:hover, .copy-all:hover {{ background: var(--accent-hover); }}
.copy-btn.copied, .copy-all.copied {{ background: var(--success); }}
.footer {{
  margin-top: 32px; padding: 20px 0; font-size: 12px; color: var(--text-secondary);
  display: flex; justify-content: space-between; flex-wrap: wrap; gap: 12px;
  border-top: 1px solid var(--border);
}}
.logo {{ vertical-align: middle; margin-bottom: 12px; display: block; }}
"""

    js = """
document.addEventListener('click', (e) => {
  const btn = e.target.closest('[data-copy]');
  if (!btn) return;
  const text = btn.getAttribute('data-copy');
  navigator.clipboard.writeText(text).then(() => {
    btn.classList.add('copied');
    const originalHtml = btn.innerHTML;
    if (btn.classList.contains('pill')) {
      btn.innerHTML = '<span class="pill-text">✓ Copied</span>';
    } else {
      btn.innerHTML = '✓ Copied';
    }
    setTimeout(() => {
      btn.classList.remove('copied');
      btn.innerHTML = originalHtml;
    }, 1200);
  });
});
"""

    footer_left = brand.FOOTER_LEFT or ""
    footer_right = brand.FOOTER_RIGHT or ""

    fonts_link = (
        f'<link rel="preconnect" href="https://fonts.googleapis.com">'
        f'<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
        f'<link rel="stylesheet" href="{attr(brand.GOOGLE_FONTS_URL)}">'
        if getattr(brand, "GOOGLE_FONTS_URL", None) else ""
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>HubSpot ICPs — {esc(source_name)}</title>
{fonts_link}
<style>{css}</style>
</head>
<body>
<div class="container">
  <div class="header">
    {logo_html}
    <h1>HubSpot Ideal Customer Profiles</h1>
    <div class="subtitle">Source: {esc(source_name)} · {len(rows)} ICPs · Field-by-field paste sheet</div>
    {toc_html}
  </div>
  {cards_html}
  <div class="footer">
    <div>{esc(footer_left)}</div>
    <div>{esc(footer_right)}</div>
  </div>
</div>
<script>{js}</script>
</body>
</html>
"""


def main():
    parser = argparse.ArgumentParser(description="Build HubSpot ICP paste sheet HTML from CSV")
    parser.add_argument("csv_path", help="Path to ICP CSV file")
    parser.add_argument("output_path", nargs="?", help="Output HTML path (defaults to alongside CSV)")
    args = parser.parse_args()

    csv_path = Path(args.csv_path)
    if not csv_path.exists():
        print(f"Error: CSV not found: {csv_path}", file=sys.stderr)
        sys.exit(1)

    with csv_path.open() as f:
        rows = list(csv.DictReader(f))
    if not rows:
        print(f"Error: CSV is empty: {csv_path}", file=sys.stderr)
        sys.exit(1)

    if args.output_path:
        out_path = Path(args.output_path)
    else:
        out_path = csv_path.parent / f"{csv_path.stem}-icps.html"

    brand = load_brand()
    html_str = build_html(rows, brand, csv_path.stem)
    out_path.write_text(html_str)
    print(f"Wrote {out_path} ({out_path.stat().st_size:,} bytes, {len(rows)} ICPs)")


if __name__ == "__main__":
    main()
